### ISSUE TITLE
Error al instalar SDKconsultoria

### ISSUE THREAD

**Issue by jmanuel001100** [sdkconsultoria/base#1]
Me sale el siguiente error

  Problem 1
    - sdkconsultoria/core dev-develop requires laravel/sanctum ^2.15 -> found laravel/sanctum[v2.15.0, v2.15.1, 2.x-dev] but it conflicts with your root composer.json require (^3.0).
    - sdkconsultoria/base dev-develop requires sdkconsultoria/core * -> satisfiable by sdkconsultoria/core[dev-develop].
    - Root composer.json requires sdkconsultoria/base dev-develop -> satisfiable by sdkconsultoria/base[dev-develop].

**Comment by hellsythe** [comment]
Hola ya esta resulto este issue.

Se actualizo la version de laravel sanctum a la versión 3
